#! /usr/local/bin/python3

import requests

res = requests.get('https://visits.evofitness.no/api/v1/locations/1e724456-b640-4b03-9b65-0cf7734aa38e/current')
a = res.json()
t = 'There are %d / %d people at Evo Oscarsgate.' % (a['current'], a['max_capacity'])
print(t)
