#!/usr/bin/env bash

git checkout develop
git pull

echo ""

echo "Enter Jira URL:"
read jiraURL
jiraURL=$(basename "$jiraURL")

echo "Enter branch name:"
read branchName

git checkout -b "feature/$jiraURL-$branchName"
